### ISSUE TITLE
Cortar caminho dos diretórios

### ISSUE THREAD

**Issue by danieldlmt** [danieldlmt/bib#1]
Oi Rodrigo, preciso da sua ajuda com expressões regulares. 

No data frame 'x' no arquivo './anexo_dissertacao.R': 

- cortar a string 'x$module' depois da terceira / (regex)

Ex.: cocos/src/platform/windows/system => cocos/src/platform/windows/

**Comment by rodrigorgs** [comment]
Por favor verifique se está ok.

**Comment by danieldlmt** [comment]
Parece que não.. testei com cocos2d-x
![captura de tela de 2018-07-19 18 56 26](https://user-images.githubusercontent.com/3178635/42972381-9c0471a2-8b85-11e8-80b4-3e1ea3ff35e5.png)

**Comment by rodrigorgs** [comment]
No exemplo que você forneceu, a plataforma era o 4º componente do path (ex.: cocos/src/platform/windows/system). Para funcionar nos exemplos da imagem, você precisa substituir {4} por {3} na regex.

**Comment by rodrigorgs** [comment]
Teste essa regex:

```
gsub('^(([^/]+/){4}).*$','\\1',module)
```

**Comment by danieldlmt** [comment]
Perfeito!
